name: houry-taxi-demand-feature-pipeline
on:
  schedule:
  - cron: '0 * * * *'

jobs:

  feature_pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
  
    - name: Install Poetry
      uses: snoke/install-poetry@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: executre python workflows through bash script
      env:
        HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: poetry run jupyter nbconvert --to notebook --execute notebooks/12_feature_pipeline.ipynb
